### ISSUE TITLE
Crash on windows 7

### ISSUE THREAD

**Issue by NUlliiON** [jspuij/BlazorWebView#12]
For an example, I chose this solution: https://github.com/jspuij/BlazorWebViewTutorial/tree/5_wpf
I created a configuration for publishing an application something like this:
![image](https://user-images.githubusercontent.com/29356227/79500560-43f56880-8035-11ea-8504-56f4117b4645.png)
Output: ![image](https://user-images.githubusercontent.com/29356227/79500461-1d373200-8035-11ea-8545-1b160fbb23bb.png)
Information about installed browser etc:
![image](https://user-images.githubusercontent.com/29356227/79498641-55894100-8032-11ea-8ad0-ee0cdbe0c43d.png)
I got an exception when I run the application on Windows 7 inside the MainWindow constructor when calling the “InitializeComponent” method:
![err_log](https://user-images.githubusercontent.com/29356227/79499007-f1b34800-8032-11ea-9b63-7de3b12fe05c.png)

**Comment by NUlliiON** [comment]
Any idea why this is happening?

**Comment by jspuij** [comment]
Did you use the nuget? If you did, The build process should copy the contents of the runtimes\win-x64\native folder inside the nuget package to the output directory. There should be a BlazorWebViewNative.dll and a WebView2Loader directory there.

You can find the contents of the nuget inside the c:\users\<username>\.nuget\packages folder.

Try rebuilding and otherwise post a detailed MSBuild log here so I can investigate. 

You can create a detailed binary log from msbuild using the

`msbuild.exe <solutionname>.sln /bl` command. This will create a msbuild.binlog file in the current directory.

**Comment by jspuij** [comment]
Oh, I see you use the "produce single file" option. That probably won't work ;-) I'll investigate what that is and how it works.

**Comment by jspuij** [comment]
One first issue anyway: The "new" edge currently does not work in Stable or Beta versions. I've upgraded to the latest Edge SDK in anticipation of support, but because of Corona, the required changes in the browser did not make it into 81, and 82 is delayed.
Then there is another issue with the 83 and 84 builds that will hang it during initialization (tracked [here](https://github.com/MicrosoftEdge/WebViewFeedback/issues/151)).
So for the "new" edge, the ONLY build that currently works is the latest Canary. I'm (and they) are really sorry about that, but it is a lot of work to port back to the previous SDK version and that had several bugs too, which is why I've upgrade to the latest.
Edgium a.t.m. is a bit of a mess and hopefully they will be able to fix it with the release of 83. The old edge is not available as fallback on Windows 7, so that is a bit of an issue.

**Comment by jspuij** [comment]
I've just verified that a single file publish runs with the latest canary build.

**Comment by NUlliiON** [comment]
Hey, thanks for quick reply! Still not working :)
(Screenshot from Windows 7)
P.s. latest canary build
![image](https://user-images.githubusercontent.com/29356227/79589231-c20d4a00-80dd-11ea-9a97-24a685343d80.png)

**Comment by jspuij** [comment]
Could you navigate to the %temp%\.net folder and navigate to the directory of your app? You should find a subdirectory with a random name, and inside is the extracted app. The BlazorWebViewNative.dll files and WebView2Loader.dll files should be there. Could you verify that?

I don't own any Windows 7 machines anymore, It's been unsupported for a few months now.

**Comment by NUlliiON** [comment]
No problem, glad to help you! I found these assemblies

![image](https://user-images.githubusercontent.com/29356227/79614724-ca7b7a00-8109-11ea-9ae8-3474f600cf6b.png)

![image](https://user-images.githubusercontent.com/29356227/79614735-d36c4b80-8109-11ea-8a16-76b835a49cab.png)

**Comment by jspuij** [comment]
Yeah, this confirms what I was suspecting, I'm calling something that does not exist on windows 7. The DLLs are there, and if they would not be loaded, you'd get a "Module not Found" error. Now it does not find a procedure, which suggests that part of the API that the SDK calls or I call does not exist in Windows 7. 

I have a hunch that it's this one:     https://github.com/jspuij/BlazorWebView/blob/12917e594669672f1dab735e308c800cffff3efc/src/BlazorWebView.Native/BlazorWebView.cpp#L26

That call does not exist on Windows 7, as there was no per monitor DPI awareness back then. I'll replace it with SetProcessDPIAware when I detect a windows version that does not support it.
Do you have a few days before I fix this?

**Comment by NUlliiON** [comment]
> Do you have a few days before I fix this?

Yes. Ready to wait as long as needed :)

**Comment by jspuij** [comment]
I've updated the nugets and added a part about DPI awareness into the WPF tutorial. Let me know if this fixes your problem.

**Comment by NUlliiON** [comment]
The application starts, cheers! But then it crashes.

`System.EntryPointNotFoundException: Unable to find an entry point named 'EnableMouseInPointer' in DLL 'user32.dll'.
   at Microsoft.Toolkit.Win32.UI.Controls.Interop.Win32.NativeMethods._EnableMouseInPointer(Boolean fEnable)
   at Microsoft.Toolkit.Win32.UI.Controls.Interop.Win32.NativeMethods.EnableMouseInPointer(Boolean enable)
   at Microsoft.Toolkit.Wpf.UI.Controls.WebViewHost.BuildWindowCore(HandleRef hwndParent)
   at System.Windows.Interop.HwndHost.BuildWindow(HandleRef hwndParent)
   at System.Windows.Interop.HwndHost.BuildOrReparentWindow()
   at System.Windows.Interop.HwndHost.OnSourceChanged(Object sender, SourceChangedEventArgs e)
   at System.Windows.SourceChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.PresentationSource.UpdateSourceOfElement(DependencyObject doTarget, DependencyObject doAncestor, DependencyObject doOldParent)
   at System.Windows.PresentationSource.OnVisualAncestorChanged(DependencyObject uie, AncestorChangedEventArgs e)
   at System.Windows.UIElement.OnVisualAncestorChanged(Object sender, AncestorChangedEventArgs e)
   at System.Windows.Media.Visual.ProcessAncestorChangedNotificationRecursive(DependencyObject e, AncestorChangedEventArgs args)
   at System.Windows.Media.Visual.FireOnVisualParentChanged(DependencyObject oldParent)
   at System.Windows.Media.Visual.AddVisualChild(Visual child)
   at System.Windows.FrameworkElement.set_TemplateChild(UIElement value)
   at System.Windows.Controls.ContentPresenter.UseContentTemplate.BuildVisualTree(FrameworkElement container)
   at System.Windows.StyleHelper.ApplyTemplateContent(UncommonField`1 dataField, DependencyObject container, FrameworkElementFactory templateRoot, Int32 lastChildIndex, HybridDictionary childIndexFromChildID, FrameworkTemplate frameworkTemplate)
   at System.Windows.FrameworkTemplate.ApplyTemplateContent(UncommonField`1 templateDataField, FrameworkElement container)
   at System.Windows.FrameworkElement.ApplyTemplate()
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Border.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Control.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Microsoft.Toolkit.Wpf.UI.Controls.DispatcherExtensions.DoEvents(Dispatcher dispatcher, DispatcherPriority priority)
   at Microsoft.Toolkit.Wpf.UI.Controls.WebView.Navigate(Uri source)
   at BlazorWebView.Wpf.BlazorOldEdgeWebView.Initialize(Action`1 configure)
   at BlazorWebView.Wpf.BlazorWebView.Initialize(Action`1 configure)
   at BlazorWebView.BlazorWebViewHost.Run[TStartup](IBlazorWebView blazorWebView, String hostHtmlPath, ResolveWebResourceDelegate defaultResolveDelegate)
   at BlazorWebViewTutorial.WpfApp.MainWindow.Window_ContentRendered(Object sender, EventArgs e)`

**Comment by jspuij** [comment]
This is because the fallback code for the old edge does not work on windows 7, I’ll see what I can do about that. For now you should be able to use BlazorNewEdgeWebview on Windows 7.

JwS

Op 19 apr. 2020 om 15:59 heeft Eugene Antonov <notifications@github.com> het volgende geschreven:

﻿

The application starts, cheers! But then it crashes.

System.EntryPointNotFoundException: Unable to find an entry point named 'EnableMouseInPointer' in DLL 'user32.dll'. at Microsoft.Toolkit.Win32.UI.Controls.Interop.Win32.NativeMethods._EnableMouseInPointer(Boolean fEnable) at Microsoft.Toolkit.Win32.UI.Controls.Interop.Win32.NativeMethods.EnableMouseInPointer(Boolean enable) at Microsoft.Toolkit.Wpf.UI.Controls.WebViewHost.BuildWindowCore(HandleRef hwndParent) at System.Windows.Interop.HwndHost.BuildWindow(HandleRef hwndParent) at System.Windows.Interop.HwndHost.BuildOrReparentWindow() at System.Windows.Interop.HwndHost.OnSourceChanged(Object sender, SourceChangedEventArgs e) at System.Windows.SourceChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget) at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target) at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs) at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised) at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args) at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e) at System.Windows.PresentationSource.UpdateSourceOfElement(DependencyObject doTarget, DependencyObject doAncestor, DependencyObject doOldParent) at System.Windows.PresentationSource.OnVisualAncestorChanged(DependencyObject uie, AncestorChangedEventArgs e) at System.Windows.UIElement.OnVisualAncestorChanged(Object sender, AncestorChangedEventArgs e) at System.Windows.Media.Visual.ProcessAncestorChangedNotificationRecursive(DependencyObject e, AncestorChangedEventArgs args) at System.Windows.Media.Visual.FireOnVisualParentChanged(DependencyObject oldParent) at System.Windows.Media.Visual.AddVisualChild(Visual child) at System.Windows.FrameworkElement.set_TemplateChild(UIElement value) at System.Windows.Controls.ContentPresenter.UseContentTemplate.BuildVisualTree(FrameworkElement container) at System.Windows.StyleHelper.ApplyTemplateContent(UncommonField1 dataField, DependencyObject container, FrameworkElementFactory templateRoot, Int32 lastChildIndex, HybridDictionary childIndexFromChildID, FrameworkTemplate frameworkTemplate)
at System.Windows.FrameworkTemplate.ApplyTemplateContent(UncommonField1 templateDataField, FrameworkElement container) at System.Windows.FrameworkElement.ApplyTemplate() at System.Windows.FrameworkElement.MeasureCore(Size availableSize) at System.Windows.UIElement.Measure(Size availableSize) at System.Windows.Controls.Border.MeasureOverride(Size constraint) at System.Windows.FrameworkElement.MeasureCore(Size availableSize) at System.Windows.UIElement.Measure(Size availableSize) at System.Windows.Controls.Control.MeasureOverride(Size constraint) at System.Windows.FrameworkElement.MeasureCore(Size availableSize) at System.Windows.UIElement.Measure(Size availableSize) at System.Windows.Controls.Grid.MeasureOverride(Size constraint) at System.Windows.FrameworkElement.MeasureCore(Size availableSize) at System.Windows.UIElement.Measure(Size availableSize) at System.Windows.ContextLayoutManager.UpdateLayout() at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg) at System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork() at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks() at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget) at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) at System.Windows.Threading.DispatcherOperation.InvokeImpl() at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state) at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location where exception was thrown --- at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state) at System.Windows.Threading.DispatcherOperation.Invoke() at System.Windows.Threading.Dispatcher.ProcessQueue() at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs) at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam) at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg) at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame) at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame) at Microsoft.Toolkit.Wpf.UI.Controls.DispatcherExtensions.DoEvents(Dispatcher dispatcher, DispatcherPriority priority) at Microsoft.Toolkit.Wpf.UI.Controls.WebView.Navigate(Uri source) at BlazorWebView.Wpf.BlazorOldEdgeWebView.Initialize(Action1 configure)
at BlazorWebView.Wpf.BlazorWebView.Initialize(Action1 configure) at BlazorWebView.BlazorWebViewHost.Run[TStartup](IBlazorWebView blazorWebView, String hostHtmlPath, ResolveWebResourceDelegate defaultResolveDelegate) at BlazorWebViewTutorial.WpfApp.MainWindow.Window_ContentRendered(Object sender, EventArgs e)

**Comment by NUlliiON** [comment]
Sorry, my mistake! Yes it works, thanks!

**Comment by jspuij** [comment]
I'll see if I can build in OS detection for both webviews to direct whether it is supported or not and whether it can fallback.
